from .base import LLMProvider

class MockProvider(LLMProvider):
    def generate_code(self, prompt: str) -> str:
        """Returns mock responses for testing."""
        if "JSON" in prompt:
            if "map each test" in prompt.lower():
                return '{"Processor_Global.VersionCheck": "getVersion", "ProcessorTest.BasicProcess": "processPacket", "ProcessorTest.SystemEnvCheck": "checkSystemEnvironment"}'
            return '["Identify state changes", "Verify return value", "Boundary check on input"]'
        return "    // Generated by MockLLM\n    EXPECT_TRUE(true);"
