import os
from abc import ABC, abstractmethod
from typing import Optional, List
import requests
import json
from dotenv import load_dotenv

# Load .env file
load_dotenv()


class LLMProvider(ABC):
    @abstractmethod
    def generate_code(self, prompt: str) -> str:
        pass


class MockProvider(LLMProvider):
    def generate_code(self, prompt: str) -> str:
        return "    // Generated by MockLLM\n    EXPECT_TRUE(true);"


class OpenAIProvider(LLMProvider):
    def __init__(self, api_key: str, model: str = "gpt-4"):
        self.api_key = api_key
        self.model = model
        try:
            import openai
            self.client = openai.OpenAI(api_key=api_key)
        except ImportError:
            raise ImportError("OpenAI client not installed. Run `pip install openai`.")

    def generate_code(self, prompt: str) -> str:
        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an expert C and C++ unit test generator using Google Test (gtest/gmock). "
                        "You handle free functions (C and C++), static functions, class member methods "
                        "(including private and protected), constructors, and destructors. "
                        "Always include boundary, equivalence partition, and MCDC test cases."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.2,
        )
        return response.choices[0].message.content


class GeminiProvider(LLMProvider):
    def __init__(self, api_key: str, model: str = "gemini-2.0-flash"):
        self.api_key = api_key
        self.model = model
        try:
            import google.generativeai as genai
            genai.configure(api_key=api_key)
            self.model_client = genai.GenerativeModel(model)
        except ImportError:
            raise ImportError(
                "Google Generative AI client not installed. Run `pip install google-generativeai`."
            )

    def generate_code(self, prompt: str) -> str:
        system_context = (
            "You are an expert C and C++ unit test generator using Google Test (gtest/gmock). "
            "You handle free functions (C and C++), static functions, class member methods "
            "(including private and protected), constructors, and destructors. "
            "Always include boundary, equivalence partition, and MCDC test cases."
        )
        full_prompt = f"System: {system_context}\n\nUser: {prompt}"
        response = self.model_client.generate_content(full_prompt)
        if response.text:
            text = response.text
            if text.startswith("```cpp"):
                text = text.replace("```cpp", "", 1)
            if text.startswith("```c"):
                text = text.replace("```c", "", 1)
            if text.startswith("```"):
                text = text.replace("```", "", 1)
            if text.endswith("```"):
                text = text[:-3]
            return text
        return "// Error: No response from Gemini."


class OllamaProvider(LLMProvider):
    def __init__(self, model: str = "qwen2.5-coder:7b", base_url: str = "http://localhost:11434"):
        self.model = model
        self.base_url = base_url
        try:
            response = requests.get(f"{self.base_url}/api/tags", timeout=2)
            if response.status_code != 200:
                print(f"[WARN] Ollama at {base_url} returned status {response.status_code}")
        except Exception as e:
            print(f"[WARN] Ollama at {base_url} not responsive: {e}")

    def generate_code(self, prompt: str) -> str:
        url = f"{self.base_url}/api/generate"
        system_context = (
            "You are an expert C and C++ unit test generator using Google Test (gtest/gmock). "
            "You handle free functions (C and C++), static functions, class member methods "
            "(including private and protected), constructors, and destructors. "
            "Always include boundary, equivalence partition, and MCDC test cases."
        )
        payload = {
            "model": self.model,
            "prompt": f"System: {system_context}\n\nUser: {prompt}",
            "stream": False,
            "options": {"temperature": 0.2},
        }
        try:
            response = requests.post(url, json=payload, timeout=120)
            if response.status_code == 200:
                result = response.json()
                text = result.get("response", "")
                if "```cpp" in text:
                    text = text.split("```cpp")[1].split("```")[0].strip()
                elif "```c" in text:
                    text = text.split("```c")[1].split("```")[0].strip()
                elif "```" in text:
                    text = text.split("```")[1].split("```")[0].strip()
                return text
            else:
                return f"// Error: Ollama returned {response.status_code}: {response.text}"
        except Exception as e:
            return f"// Error: Ollama connection failed: {e}"


class LLMClient:
    def __init__(self):
        api_key = os.getenv("LLM_API_KEY")
        provider_pref = os.getenv("LLM_PROVIDER", "").lower()
        ollama_model = os.getenv("OLLAMA_MODEL", "qwen2.5-coder:7b")

        # 1. Explicit preference
        if provider_pref == "ollama":
            print(f"[INFO] Using Ollama Provider ({ollama_model}).")
            self.provider = OllamaProvider(model=ollama_model)
            return

        # 2. Key-based detection
        if api_key:
            if api_key.startswith("AIza"):
                self.provider = GeminiProvider(api_key)
                print("[INFO] Using Gemini Provider.")
                return
            elif api_key.startswith("sk-"):
                self.provider = OpenAIProvider(api_key)
                print("[INFO] Using OpenAI Provider.")
                return

        # 3. Auto-detect Ollama
        try:
            response = requests.get("http://localhost:11434/api/tags", timeout=1)
            if response.status_code == 200:
                models = [m["name"] for m in response.json().get("models", [])]
                if ollama_model not in models and ":" not in ollama_model:
                    match = next((m for m in models if m.startswith(ollama_model)), None)
                    if match:
                        ollama_model = match
                if any(m.startswith(ollama_model) for m in models):
                    print(f"[INFO] Auto-detected Ollama at localhost. Using {ollama_model}.")
                    self.provider = OllamaProvider(model=ollama_model)
                    return
        except Exception:
            pass

        # 4. Fallback to Mock
        print("[WARN] No valid LLM provider found. Using Mock Provider.")
        self.provider = MockProvider()

    def generate_test_body(self, function_signature: str, strategy: dict) -> str:
        prompt = self._construct_prompt(function_signature, strategy)
        try:
            return self.provider.generate_code(prompt)
        except Exception as e:
            print(f"[ERROR] LLM Generation failed: {e}")
            return f"// Error: {e}"

    def identify_test_strategy(self, signature: str, body_code: str, language: str, technical_context: dict) -> List[str]:
        """
        Asks the LLM to analyze code logic and unify it with technical requirements 
        (boundaries, EP, mocks, etc.) into a single master test strategy.
        """
        boundary_txt = "\n".join([f"- {c}" for c in technical_context.get("boundary_cases", [])])
        ep_txt = "\n".join([f"- {c}" for c in technical_context.get("equivalence_partition_cases", [])])
        mocks_txt = "\n".join([f"- {c}" for c in technical_context.get("mocks_needed", [])])
        mcdc_txt = "\n".join([f"- {c}" for c in technical_context.get("mcdc_cases", [])])

        prompt = f"""
You are an expert Test Architect. Analyze the following {language} function and produce a UNIFIED, OPTIMIZED set of high-quality test scenarios.

### Function details:
Signature: `{signature}`
Implementation:
```
{body_code}
```

### Technical Requirements to Integrate:
These are the technical baseline requirements (Boundary values, Equivalence Partitions, and Mocks) you MUST consider and integrate into your logic analysis:

**Boundary Conditions:**
{boundary_txt or "None identified"}

**Equivalence Partitions:**
{ep_txt or "None identified"}

**External Dependencies / Mocks:**
{mocks_txt or "None identified"}

**Logical Paths (MCDC):**
{mcdc_txt or "None identified"}

### Objective:
Identify a **minimal but robust** set of test scenarios. Do NOT brute-force every possible permutation. Instead, focus on:
1. **Critical Logic Paths:** Covered by the implementation logic.
2. **Risk-Based Scenarios:** Where the code is most likely to fail (e.g., edge cases identified in boundaries).
3. **Internal Logic Flow:** Map the technical boundaries to specific behavioral expectations (e.g., "Verify add(0, 0) returns 0" instead of just "Boundary: zero").

Ensure ALL identified boundary values and partitions are addressed, but consolidate them where it makes sense (e.g., one scenario can cover multiple boundaries if logical).

Format: Output ONLY a JSON list of strings.
Example: ["Check result when value is exactly 0", "Verify error when buffer is full", "Mock database failure during record insertion"]
"""
        try:
            response = self.provider.generate_code(prompt)
            # Try to parse as JSON list
            import json
            import re
            
            resp_text = response.strip()
            
            # 1. Try to find a JSON list anywhere in the response
            json_match = re.search(r'\[\s*".*"\s*\]', resp_text, re.DOTALL)
            if json_match:
                try:
                    cases = json.loads(json_match.group(0))
                    if isinstance(cases, list):
                        return [str(c) for c in cases]
                except:
                    pass
            
            # 2. Try to find a JSON block via markdown tags
            if "```json" in resp_text:
                json_block = resp_text.split("```json")[1].split("```")[0].strip()
                try:
                    cases = json.loads(json_block)
                    if isinstance(cases, list):
                        return [str(c) for c in cases]
                except:
                    pass

            # 3. Fallback: Parse bullet points
            bullet_matches = re.findall(r'(?:^|\n)(?:[-*]|\d+\.)\s*(.+)', resp_text)
            if bullet_matches:
                return [m.strip() for m in bullet_matches]
            
            # 4. Final fallback: If response is short enough and has multiple lines, treat each line as a case
            lines = [l.strip() for l in resp_text.split('\n') if l.strip() and not l.startswith('```')]
            if 0 < len(lines) < 10:
                return lines

            return ["Deep Logic Analysis (LLM response format not recognized)"]
        except Exception as e:
            print(f"[ERROR] Logic strategy identification failed for {signature}: {e}")
            return [f"Error identifying strategy: {e}"]

    def _construct_prompt(self, signature: str, strategy: dict) -> str:
        language = strategy.get("language", "C++")
        kind = strategy.get("kind", "free_function")
        is_static = strategy.get("is_static", False)
        access_spec = strategy.get("access_specifier", "none")
        class_name = strategy.get("class_name", "")

        # Build bullet lists
        cases_txt = "\n".join(
            [f"- {c}" for c in strategy.get("suggested_test_cases", [])]
        )
        
        # Optional baseline context if still provided
        boundary_txt = "\n".join([f"- {c}" for c in strategy.get("boundary_cases", [])])
        ep_txt = "\n".join([f"- {c}" for c in strategy.get("equivalence_partition_cases", [])])
        baseline_info = ""
        if boundary_txt or ep_txt:
            baseline_info = f"\nTechnical baseline for reference:\n{boundary_txt}\n{ep_txt}\n"

        # Calling convention hints
        fixture_context = ""
        if class_name and class_name not in ("UnknownClass", ""):
            if is_static:
                fixture_context = (
                    f"This is a STATIC method of class `{class_name}`. "
                    f"Call it as `{class_name}::{signature.split('(')[0].split()[-1]}(...)`."
                )
            elif access_spec in ("private", "protected"):
                fixture_context = (
                    f"This is a {access_spec.upper()} method of class `{class_name}`. "
                    f"Test it via the public API, a friend test class, or a test-only subclass."
                )
            else:
                fixture_context = (
                    f"Assume you are inside a Google Test fixture that has an instance of "
                    f"`{class_name}` named `obj`. Use `obj.<method>(...)` to call member functions."
                )

        return f"""
Generate the body of a {language} Google Test (gtest) for the following function:
`{signature}`

Function Kind: {kind}
Language: {language}

## Test Scenarios to Implement (MASTER LIST)
{cases_txt}
{baseline_info}
## Mocks Needed
{strategy.get('mocks_needed', [])}

{fixture_context}

Output ONLY the C++ code inside the TEST body (do not output the TEST macro itself or #includes).
Ensure all scenarios listed above are covered by appropriate EXPECT_* or ASSERT_* assertions.
"""
