import os
from abc import ABC, abstractmethod
from typing import Optional, List
import requests
import json
from dotenv import load_dotenv

# Load .env file
load_dotenv()

class LLMProvider(ABC):
    @abstractmethod
    def generate_code(self, prompt: str) -> str:
        pass

class MockProvider(LLMProvider):
    def generate_code(self, prompt: str) -> str:
        # Return a simple deterministic placeholder
        return "    // Generated by MockLLM\n    EXPECT_TRUE(true);"

class OpenAIProvider(LLMProvider):
    def __init__(self, api_key: str, model: str = "gpt-4"):
        self.api_key = api_key
        self.model = model
        try:
            import openai
            self.client = openai.OpenAI(api_key=api_key)
        except ImportError:
            raise ImportError("OpenAI client not installed. Run `pip install openai`.")

    def generate_code(self, prompt: str) -> str:
        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": "You are an expert C++ Unit Test generator using Google Test."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.2
        )
        return response.choices[0].message.content

class GeminiProvider(LLMProvider):
    def __init__(self, api_key: str, model: str = "gemini-2.0-flash"):
        self.api_key = api_key
        self.model = model
        try:
            import google.generativeai as genai
            genai.configure(api_key=api_key)
            self.model_client = genai.GenerativeModel(model)
        except ImportError:
            raise ImportError("Google Generative AI client not installed. Run `pip install google-generativeai`.")

    def generate_code(self, prompt: str) -> str:
        # Provide system context in prompt since Gemini Pro doesn't always support system roles the same way
        full_prompt = f"System: You are an expert C++ Unit Test generator using Google Test.\n\nUser: {prompt}"
        response = self.model_client.generate_content(full_prompt)
        # Handle safety blocks or empty responses
        if response.text:
            # Clean up markdown code blocks if present
            text = response.text
            if text.startswith("```cpp"):
                text = text.replace("```cpp", "", 1)
            if text.startswith("```"):
                text = text.replace("```", "", 1)
            if text.endswith("```"):
                text = text[:-3]
            return text
        return "// Error: No response from Gemini."

class OllamaProvider(LLMProvider):
    def __init__(self, model: str = "qwen2.5-coder:7b", base_url: str = "http://localhost:11434"):
        self.model = model
        self.base_url = base_url
        # Check if Ollama is responsive
        try:
            response = requests.get(f"{self.base_url}/api/tags", timeout=2)
            if response.status_code != 200:
                print(f"[WARN] Ollama at {base_url} returned status {response.status_code}")
        except Exception as e:
            print(f"[WARN] Ollama at {base_url} not responsive: {e}")

    def generate_code(self, prompt: str) -> str:
        url = f"{self.base_url}/api/generate"
        payload = {
            "model": self.model,
            "prompt": f"System: You are an expert C++ Unit Test generator using Google Test.\n\nUser: {prompt}",
            "stream": False,
            "options": {
                "temperature": 0.2
            }
        }
        try:
            response = requests.post(url, json=payload, timeout=120)
            if response.status_code == 200:
                result = response.json()
                text = result.get("response", "")
                
                # Basic cleanup of markdown
                if "```cpp" in text:
                    text = text.split("```cpp")[1].split("```")[0].strip()
                elif "```" in text:
                    text = text.split("```")[1].split("```")[0].strip()
                
                return text
            else:
                return f"// Error: Ollama returned {response.status_code}: {response.text}"
        except Exception as e:
            return f"// Error: Ollama connection failed: {e}"

class LLMClient:
    def __init__(self):
        # Determine provider
        api_key = os.getenv("LLM_API_KEY")
        provider_pref = os.getenv("LLM_PROVIDER", "").lower()
        ollama_model = os.getenv("OLLAMA_MODEL", "qwen2.5-coder:7b")
        
        # 1. Explicit Preference
        if provider_pref == "ollama":
            print(f"[INFO] Using Ollama Provider ({ollama_model}).")
            self.provider = OllamaProvider(model=ollama_model)
            return
        
        # 2. Key-based detection
        if api_key:
            if api_key.startswith("AIza"):
                 self.provider = GeminiProvider(api_key)
                 print("[INFO] Using Gemini Provider.")
                 return
            elif api_key.startswith("sk-"):
                 self.provider = OpenAIProvider(api_key)
                 print("[INFO] Using OpenAI Provider.")
                 return

        # 3. Auto-detect Ollama if no key or key is invalid
        try:
            response = requests.get("http://localhost:11434/api/tags", timeout=1)
            if response.status_code == 200:
                # Check if the preferred model exists locally
                models = [m['name'] for m in response.json().get('models', [])]
                if ollama_model not in models and ":" not in ollama_model:
                     # Try to find recent match if tag missing
                     match = next((m for m in models if m.startswith(ollama_model)), None)
                     if match:
                         ollama_model = match
                
                if any(m.startswith(ollama_model) for m in models):
                    print(f"[INFO] Auto-detected Ollama at localhost. Using {ollama_model}.")
                    self.provider = OllamaProvider(model=ollama_model)
                    return
        except:
            pass

        # 4. Fallback to Mock
        print("[WARN] No valid LLM provider found (API Key missing or Ollama unreachable). Using Mock Provider.")
        self.provider = MockProvider()

    def generate_test_body(self, function_signature: str, strategy: dict) -> str:
        prompt = self._construct_prompt(function_signature, strategy)
        try:
            return self.provider.generate_code(prompt)
        except Exception as e:
            print(f"[ERROR] LLM Generation failed: {e}")
            return f"// Error: {e}"

    def _construct_prompt(self, signature: str, strategy: dict) -> str:
        # Build a prompt using the strategy details
        cases = "\n".join([f"- {c}" for c in strategy.get('suggested_test_cases', [])])
        
        # Determine if we should mention 'obj'
        fixture_context = ""
        if 'class_name' in strategy and strategy['class_name'] != "UnknownClass":
            fixture_context = f"Assume you are inside a Google Test fixture that has an instance of the class `{strategy['class_name']}` named `obj`. Use `obj.<method>` to call member functions."

        return f"""
Generate the body of a C++ Google Test (gtest) for the function:
`{signature}`

Strategy Context:
{cases}

Mocks needed:
{strategy.get('mocks_needed', [])}

{fixture_context}

Output ONLY the C++ code inside the TEST body (do not output the TEST macro itself, or imports).
        """
